spring:
  application:
    name: xsglxt
  datasource:
    url: jdbc:mysql://localhost:3306/xsglxt?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: "112358"
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081

mybatis-plus:
  type-aliases-package: com.akira.xsglxt.entity
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
